version: '3.4'
 
networks:
  regaloparatiapi-dev:
    driver: bridge 
 
services:
  regaloparatiapi:
    image: regaloparatiapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=rptdb;username=rptadmin;password=rptadmin"
    networks:
      - regaloparatiapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "rptadmin"
      POSTGRES_PASSWORD: "rptadmin"
      POSTGRES_DB: "rptdb"
    networks:
      - regaloparatiapi-dev
volumes:
  db_volume:
         
